# Generated by Django 5.2.7 on 2025-10-13 01:59

import cms.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliatedUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_email', models.EmailField(max_length=254)),
                ('university_name', models.CharField(max_length=254)),
                ('university_title', models.CharField(max_length=254)),
                ('university_photo', models.ImageField(blank=True, null=True, upload_to='university_photos/', validators=[cms.validators.validate_image_size, cms.validators.validate_image_format])),
            ],
        ),
    ]
