# Generated by Django 5.2.7 on 2025-10-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('guest_count', models.IntegerField(default=0)),
                ('comments', models.TextField(blank=True)),
                ('items', models.ManyToManyField(to='firstapp.menuitem')),
            ],
        ),
    ]
