# Generated by Django 5.2.7 on 2025-10-10 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='items',
        ),
    ]
